export enum actionTypes {
  REGISTER = 'register',
  LOGIN = 'login',
  LOGOUT = 'logout',
  REFRESH_TOKEN = 'refreshToken',
  FETCH_GET_TODO = 'fetchGetTodo',
  GET_TODO = 'getTodo',
  FETCH_CREATE_TODO = 'fetchCreateTodo',
  CREATE_TODO = 'createTodo',
  FETCH_UPDATE_TODO = 'fetchUpdateTodo',
  UPDATE_TODO = 'updateTodo',
  FETCH_COMPLETE_TODO = 'fetchCompleteTodo',
  COMPLETE_TODO = 'completeTodo',
  FETCH_DELETE_TODO = 'fetchDeleteTodo',
  DELETE_TODO = 'deleteTodo',
  FETCH_DELETE_COMPLETED_TODOS = 'fetchDeleteCompletedTodo',
  DELETE_COMPLETED_TODOS = 'deleteCompletedTodo',
}
